### ISSUE TITLE
Get the caption of the post

### ISSUE THREAD

**Issue by mdaffa48** [sasmeee/igdl#3]
This is not an issue, however. Can you add more data to the result? Such as giving the caption of the post.

**Comment by sasmeee** [comment]
Hey there! Thanks for reaching out. While your suggestion isn't exactly an issue, we appreciate your input! We'll definitely consider adding more data to the results, including post captions, in our next update. Stay tuned for improvements, and feel free to share any more thoughts you may have. Happy coding!
